name: Search MYSQL creds

on: [push]

jobs:
  search:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get branch name
        id: branch-name
        run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"
      - name: Search MYSQL creds
        run: git grep -E 'MYSQL_\w+\s*=' $(git diff --name-only --diff-filter=ACMRTUXB origin/${{ steps.branch-name.outputs.branch }}) || echo "not found"
