name: Grep MYSQL

on: [push]

jobs:
  grep:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Grep MYSQL
      run: git grep -E 'MYSQL_\w+\s*='
