name: Recherche MYSQL_

on:
  push:
    branches:
      - master

jobs:
  recherche-mysql:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout du code
      uses: actions/checkout@v2

    - name: Recherche MYSQL_
      run: |
        git grep 'MYSQL_\w+\s*=' $(git diff --name-only --diff-filter=ACMRTUXB HEAD~ HEAD) || echo "Aucune correspondance trouvée"
