name: Recherche MYSQL_

on:
  push:
    branches:
      - master

jobs:
  recherche-mysql:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout du code
      uses: actions/checkout@v2

    - name: Recherche MYSQL_
      run: |
        git rev-parse --verify HEAD > /dev/null 2>&1 && git grep 'MYSQL_\w+\s*=' $(git diff --name-only --diff-filter=ACMRTUXB $(git rev-parse --short=8 master)~ $(git rev-parse --short=8 master)) || echo "Aucune correspondance trouvée"
