name: Search MYSQL variables

on: [push]

jobs:
  search:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Search MYSQL variables
      run: git grep 'MYSQL_\w+\s*=' $(git diff --name-only --diff-filter=ACMRTUXB HEAD~) || true
