name: Recherche MYSQL_

on:
  push:
    branches:
      - master

jobs:
  recherche-mysql:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout du code
      uses: actions/checkout@v2

    - name: Recherche MYSQL_
      run: |
git grep -E 'MYSQL_\w+\s*=' || echo "Aucune correspondance trouvée"
