name: Recherche MYSQL

on:
  push:
    branches:
      - main

jobs:
  recherche-mysql:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout du dépôt
      uses: actions/checkout@v2

    - name: Recherche de la regex MYSQL
      run: |
        git grep 'MYSQL_\w+\s*=' $(git diff --name-only --diff-filter=ACMRTUXB ${{ github.event.before }} ${{ github.event.after }}) || true
